parameters:
#    sales_engine_online_desafio.example.class: SalesEngineOnline\DesafioBundle\Example

services:
#    sales_engine_online_desafio.example:
#        class: %sales_engine_online_desafio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
